### PR TITLE
Prevent creation of non-existing namespaces in apps

### PR DESCRIPTION
**Pull request by Nebel54**
As stated in #503 Drupal throws an error when using the current Component Library module. To prevent this, I needed to:

- Move the generation of the namespaces after the compile process (from an npm run script to a webpack `RunScriptAfterEmit` plugin), so the generator can check if all generated namespaces exist in dist/
- Change the existing namespace transform functions a bit to also return the relative path for the file checks.
- Add another flag `skipFileExistenceCheck`, to allow different design systems to skip this file check, as patternlab needs all components of course.

I am not quite sure if the namespace generation really needs to run for patternlab before the webpack build, but I just left it in `gulp compile:startup`, so it runs before and after the webpack build now.

### CODE REVIEW

**Comment by illepic** [comment]
Will take a look at this!

**Comment by illepic** [comment]
Noting here that I haven't forgotten about this. Circling around to it this week.

**Comment by jcandan** [comment]
I can vouch for this patch; this fixed the `Uncaught PHP Exception Twig\Error\LoaderError` I was getting. See #543.

**Comment by lunitin** [comment]
This PR also fixed my issue with Drupal 8.7.1

> I can vouch for this patch; this fixed the `Uncaught PHP Exception Twig\Error\LoaderError` I was getting. See #543.

This PR also fixed the same issue that cropped up with my Drupal 8.7.1 install.

**Comment by Nebel54** [comment]
As a quick update: This PR will not make it into particle. PR #552 already provides a short-term solution and in #554 will contain a cleaner long-term-solution.

**Pull request closed without merging**
