### PR TITLE
TASK :: Revise Drupal + Pattern Lab Directory Structure

### PR DESCRIPTION
**Pull request by jryanconklin**
# Pull Request

Closes Issue #827 

## Issue Description

Revise directory structure and docs for easier understanding.

## Summary of Changes

Revise the directory structure and update Drupal documentation. This PR:
* Update `apps/drupal` => `apps/drupal-default`to match `thing-designsystem` naming
* Update Drupal Theme Path and rename `apps/drupal-default/particle_theme`
* Update Drupal Module and rename `apps/drupal-default/particle_helper`
* Update `apps/node-pl` => `apps/node-pl-default`to match `thing-designsystem` naming

### CODE REVIEW

**Comment by mike-potter** [comment]
I feel like `node-pl-default` should just be `pl-default`.  Don't see the need for the `node` distinction anymore.  Also not generally a fan of `-default` everywhere.  You could easily have a convention of `thing-designsystem` where if `designsystem` was not specified it would use `default` as the default.  

Don't hugely care as long as the URLs dont end up being even longer for getting to PL from Drupal `/dist/apps/node-pl-default/pl` or something.

Finally, in actual Drupal sites using Octane, the theme will be in `/project/themes/THEMENAME` and the PL design system (Particle) will be in `/project/design/particle` (until Particle moves to being an actual node dependency, at which point the "source" patterns would be in `project/design/DESIGNNAME`.  So just want to ensure Particle config will still allow that kind of directory structure.

**Comment by illepic** [comment]
If we're in here making these changes (finally!), let's drop "node" off the app name.

@mike-potter, we're looking for a quick naming convention to tie an "app" to a "design system", since a drupal theme and a pattern lab (and, eventually, a storybook) consume and represent exactly one design system. We're just looking for a quick glance way of knowing "what is this app showing off?" to make the eventual particle 11 generators work.

Those generators will effectively ask us these questions in this order:

1. What do you want to name your design system?
1. Where should it be placed?
1. Which apps (drupal|pl) would you like to consume this design system?
1. Where should those apps live?

**Comment by illepic** [comment]
Whoops, hit tab and accidentally closed! My bad!

**Comment by jryanconklin** [comment]
> I feel like `node-pl-default` should just be `pl-default`. Don't see the need for the `node` distinction anymore. Also not generally a fan of `-default` everywhere. You could easily have a convention of `thing-designsystem` where if `designsystem` was not specified it would use `default` as the default.
> 
> Don't hugely care as long as the URLs dont end up being even longer for getting to PL from Drupal `/dist/apps/node-pl-default/pl` or something.
> 
> Finally, in actual Drupal sites using Octane, the theme will be in `/project/themes/THEMENAME` and the PL design system (Particle) will be in `/project/design/particle` (until Particle moves to being an actual node dependency, at which point the "source" patterns would be in `project/design/DESIGNNAME`. So just want to ensure Particle config will still allow that kind of directory structure.

Default isn't really meant to be kept and I actually like it as a paint point to rename your DS from `default`. But moreover this will clear the way to setting a DS name as config in 11. I think `default` is fine as a starting point but it can as easily be `base` (though I question the labor involved to make that change on 10). TLDR: this will be useful for generators and just basic cognitive understanding of what apps are doing.

I don't think the docs should count on Octane project structure. That tooling has everything it needs to know where to put Particle. Whereas the docs need to cover how to use this elsewhere.

**Comment by jryanconklin** [comment]
@illepic I'll update to remove `node` from `apps/node-pl-default`

**Comment by jryanconklin** [comment]
@illepic @mike-potter Updated PR:
* `apps/node-pl-default` => `apps/pl-default`
* Config for `app-pl-node` => `app-pl`

**Comment by mike-potter** [comment]
OK, that looks good.

I wasn't asking for a change in docs, I just wanted to make sure that the directory structure needed for Octane can be supported.  Sounds like the answer is "yes".  And I am fine with `default` being a "pain point" to encourage projects to name their design system and theme correctly.

@Bloom so in your questions, Octane would answer:

What do you want to name your design system (default: "default")? `octane`
Where should it be placed (default: source/default)? `project/design/octane`
Which apps (drupal|pl) would you like to consume this design system (default: both selected)? `both`
Where should those apps live (default: apps/)?
*this question needs to be asked for each app*
drupal: `project/themes/octane`
pl: `project/apps/pl` (or something like that...we don't currently use PL outside of the DESIGN_PATH but supporting this same app concept would be useful)

**Comment by illepic** [comment]
This no longer run locally via `npm start` (even after an `npm run setup`). I'm looking into why now.

**Comment by jryanconklin** [comment]
Boo. Okay. I can take a look, too. Did you pull without doing a full reset? I have been nuking everything between steps and verifying with ‘npm run ci’

**Comment by jryanconklin** [comment]
@illepic, confirmed on my local machine. Are you deleting node modules and removing old dist?

**Comment by illepic** [comment]
NOPE. That's my machine due to some port mappings I had to do recently for Docksal. Carry on! I'll get this figured out.

**Pull request merged**
